name = "beslisboom_bellen_stage"
version = "1.0.0"
target = "javascript"

[dependencies]
lustre = "4.6.4"
birl = ">= 1.7.1 and < 2.0.0"
plinth = ">= 0.5.7 and < 1.0.0"
gleam_stdlib = ">= 0.54.0 and < 1.0.0"
gleam_decode = ">= 1.7.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
lustre_dev_tools = "~> 1.0"
