name = "beslisboom_bellen_stage"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_json = "1.0.1"
lustre = "4.6.3"
gleam_stdlib = ">= 0.43.0 and < 1.0.0"
birl = ">= 1.7.1 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
lustre_dev_tools = "~> 1.0"
